package files

import (
	"fmt"
	"github.com/wokacz/mamba/internal/words"
	"os"
)

func (f Files) getConfigFileContent(projectName string) string {
	tomlProjectName := words.ToKebabCase(projectName)
	return fmt.Sprintf(`# mambaPy configuration file
# https://www.github.com/wokacz/mamba
# This file is generated by the mambaPy CLI
# Do not modify this file manually

[mamba]
project_name = "%s"
version = "0.1.0"
debug = false

[generated]
resources = [
	"users",
]
`, tomlProjectName)
}

func (f Files) CreateConfigFile(projectName string) error {
	file, err := os.Create(fmt.Sprintf("%s/mamba.toml", projectName))
	if err != nil {
		fmt.Println(err)
		return err
	}

	defer func(file *os.File) {
		err := file.Close()
		if err != nil {
			fmt.Println(err)
		}
	}(file)

	content := f.getConfigFileContent(projectName)

	_, err = file.WriteString(content)
	if err != nil {
		fmt.Println(err)
		return err
	}

	return err
}
